---
version: '2'
services:

  postgres-dev:
    image: postgres
    container_name: isi-dev-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    command: [ "-c", "shared_buffers=256MB", "-c", "max_connections=200" ]

  postgres-prod:
    image: postgres
    container_name: isi-prod-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    command: [ "-c", "shared_buffers=256MB", "-c", "max_connections=200" ]